# group_vars/jenkins.yml

jenkins_url: "http://localhost:8080"
jenkins_admin_user: "admin"
# Ya no necesitas vault_jenkins_api_token aquí, porque usaremos admin/AdminPass123! (según JCasC) para
# invocar la API. Si deseas cifrarlo, puedes usar Ansible Vault:
jenkins_admin_password: "AdminPass123!"

jenkins_plugins:
  - workflow-aggregator
  - git
  - credentials-binding
  - ansible
  - docker-workflow

ssh_creds:
  id: "git-ssh-key"
  description: "Clave SSH para Git"
  username: "git"
  private_key_path: "~/.ssh/id_rsa"

dockerhub_creds:
  id: "dockerhub-creds"
  description: "Credenciales DockerHub"
  username: "{{ vault_dockerhub_user }}"
  password: "{{ vault_dockerhub_pass }}"

jenkins_jobs:
  - name: "Webapp-CI"
    xml: "webapp-ci.xml"
  - name: "Infra-IaC"
    xml: "infra-iac.xml"
  - name: "Smoke-Tests"
    xml: "smoke-tests.xml"

vault_dockerhub_user: "jsegrod1512"
vault_dockerhub_pass: "dckr_pat_o5qHaQXrA8UlhHmqNWNLsdjdzvM"
