---
# Paquete de Java requerido por Jenkins (OpenJDK 17 en Ubuntu 24.04)
java_package: "openjdk-17-jdk" 

# URL de la clave GPG oficial de Jenkins para verificar el repositorio
jenkins_gpg_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key" 

# Entrada para /etc/apt/sources.list.d/jenkins.list (repositorio oficial de Jenkins)
jenkins_repo_entry: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" 

# Nombre del paquete que se instalará (desde el repositorio de Jenkins)
jenkins_package: "jenkins"  

# Nombre del servicio systemd de Jenkins
jenkins_service: "jenkins" 

# Puerto en el que Jenkins escuchará HTTP (por defecto 8080)
jenkins_port: 8080
