# Variables para instalación básica de Jenkins
java_package: "openjdk-17-jdk"
jenkins_gpg_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
jenkins_repo_entry: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
jenkins_package: "jenkins"
jenkins_service: "jenkins"
jenkins_port: 8080

# Usuario y contraseña de administrador de Jenkins a configurar
jenkins_admin_user: "admin"        
jenkins_admin_password: "SuContra123!"    

# Lista de plugins
jenkins_plugins:
  - git
  - workflow-aggregator
  - docker-workflow
  - ldap
  - role-strategy
  - credentials-binding
  - email-ext
  - blueocean
  - matrix-auth
  - ansicolor

extra_plugins:
      - "job-dsl"
      - "pipeline-utility-steps"
