ldap_uri:    "ldap://172.16.1.12"
ldap_domain:       cajacelia.es
ldap_organization: CajaCelia
ldap_root_dn:      "cn=admin,dc=cajacelia,dc=es"
ldap_admin_user:   admin
ldap_root_pass:    "OtroPasswordSeguro"
base_dn:           "dc=cajacelia,dc=es"

group_gids:
  Desarrolladores: 10001
  Clientes: 10002