ldap:
  uri:          "ldap://172.16.1.12"
  base_dn:      "dc=cajacelia,dc=es"
  domain:       "cajacelia.es"
  organization: "CajaCelia"

ldap_groups:
  Desarrolladores: 10001
  Clientes:        10002

ldap_admin_user: "admin"
ldap_admin:
  password: "{{ vault_ldap_root_pass }}"

vault_ldap_root_pass: "C4mbia_Esta_Contraseña_Por_Vault"

bind_dn: "cn={{ ldap_admin_user }},{{ ldap.base_dn }}"
bind_pw: "{{ ldap_admin.password }}"