---
- import_playbook: playbooks/webserver.yml
- import_playbook: playbooks/database.yml
- import_playbook: playbooks/deploy_database.yml
- import_playbook: playbooks/ldap.yml
- import_playbook: playbooks/install_ldap.yml
- import_playbook: playbooks/deploy_ldap_roles.yml
- import_playbook: playbooks/manage_users_ldap.yml
- import_playbook: playbooks/jenkins.yml
- import_playbook: playbooks/clear.yml
- import_playbook: playbooks/backup.yml