---
- import_playbook: playbooks/install_ldap.yml
- import_playbook: playbooks/manage_users_ldap.yml
- import_playbook: playbooks/clients_ldap.yml
- import_playbook: playbooks/database.yml
- import_playbook: playbooks/deploy_database.yml
- import_playbook: playbooks/webapp.yml
- import_playbook: playbooks/role_setup.yml
- import_playbook: playbooks/install_jenkins.yml
# Playbook que se ejecuta al configurar admin:contraseña en jenkins
# - import_playbook: playbooks/jenkins_plugins.yml
# Playbook que se ejecuta al configurar admin:contraseña en jenkins
# - import_playbook: playbooks/deploy_jenkins.yml
- import_playbook: playbooks/clear.yml
# Playbook para realizar backups de jenkins
# - import_playbook: playbooks/backup.yml