# playbook_backup_ldap.yml
- name: Backup completo de OpenLDAP
  hosts: ldap
  become: true
  tasks:
    - name: Crear directorio de backups
      file:
        path: /var/backups/ldap
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Volcar DIT a LDIF con slapcat
      command: slapcat -v -l /var/backups/ldap/ldap-{{ ansible_date_time.date }}.ldif
      register: backup_run

    - name: Mostrar resumen de backup
      debug:
        msg: "Backup realizado: {{ backup_run.stdout_lines | join('\n') }}"
