- name: Configurar clientes LDAP con nslcd
  hosts: clients
  become: yes
  vars_files:
    - ../users/users.yml   # si necesitas aprovisionar usuarios locales o pruebas
  tasks:
    - name: Instalar paquetes necesarios
      apt:
        name:
          - nslcd
          - libnss-ldapd
          - ldap-utils
          - nscd
          - libpam-ldapd
        state: present
        update_cache: yes

    - name: Deshabilitar configuración interactiva de libpam-ldapd
      debconf:
        name: libpam-ldapd
        question: "pam/ldapns/ldap-server"
        value: "{{ ldap_uri }}"
        vtype: string

    - name: Crear configuración de nslcd
      template:
        src: ../templates/nslcd.conf.j2
        dest: /etc/nslcd.conf
        owner: root
        group: root
        mode: '0600'

    - name: Configurar nsswitch para usar LDAP
      template:
        src: ../templates/nsswitch.conf.j2
        dest: /etc/nsswitch.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configurar PAM para cuentas LDAP
      template:
        src: ../templates/common-account.j2
        dest: /etc/pam.d/common-account
        owner: root
        group: root
        mode: '0644'

    - name: Reiniciar servicios nslcd, nscd
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - nslcd
        - nscd