---
- name: Configurar clientes Linux para autenticarse contra OpenLDAP
  hosts: clients
  become: true
  vars:
    ldap_uri: "ldap://172.16.1.12"
    ldap_base: "dc=cajacelia,dc=es"
    ldap_bind_dn: "cn=admin,dc=cajacelia,dc=es"
    ldap_bind_pw: "OtroPasswordSeguro"
  tasks:
    - name: Instalar SSSD, NSS/PAM y utilidades LDAP
      apt:
        name:
          - sssd
          - libnss-sss
          - libpam-sss
          - ldap-utils
        state: present
        update_cache: yes

    - name: Copiar fichero de configuración sssd.conf
      template:
        src: ../templates/sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: 0600

    - name: Configurar nsswitch para usar sss
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^passwd:'
        line: 'passwd:         files sss'
        backup: yes
      notify: restart sssd

    - name: Configurar group en nsswitch
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^group:'
        line: 'group:          files sss'
        backup: yes
      notify: restart sssd

    - name: Configurar shadow en nsswitch
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^shadow:'
        line: 'shadow:         files sss'
        backup: yes
      notify: restart sssd

    - name: Asegurar que SSSD arranca al inicio
      service:
        name: sssd
        state: started
        enabled: yes

  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
