---
- name: Instalar y configurar MySQL en el host database
  hosts: database
  become: yes
  vars_files:
    - ../group_vars/database.yml

  tasks:
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Instalar módulo Python para conectividad MySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Asegurar línea bind-address en mysqld.cnf
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: "bind-address = {{ mysql_bind_address }}"
        backup: yes

    - name: Reiniciar servicio MySQL
      service:
        name: mysql
        state: restarted
        enabled: yes

    