---
- name: Desplegar base de datos MySQL en el host database
  hosts: database
  become: yes
  vars_files:
    - ../group_vars/database.yml

  tasks:
    - name: Eliminar base de datos de la app si existe
      mysql_db:
        name: "{{ app_db.name }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear base de datos de la app
      mysql_db:
        name: "{{ app_db.name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear usuario para la app con todos los privilegios
      mysql_user:
        name: "{{ app_db.user }}"
        password: "{{ app_db.password }}"
        priv: "{{ app_db.name }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
