---
- name: Desplegar base de datos MySQL en el host database
  hosts: database
  become: yes
  vars_files:
    - ../group_vars/database.yml

  tasks:
    - name: Eliminar base de datos de la app si existe
      mysql_db:
        name: "{{ app_db.name }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear base de datos de la app
      mysql_db:
        name: "{{ app_db.name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear usuario para la app con todos los privilegios
      mysql_user:
        name: "{{ app_db.user }}"
        password: "{{ app_db.password }}"
        priv: "{{ app_db.name }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Copiar plantilla de esquema SQL a la máquina de BBDD
      template:
        src: ../templates/app_schema.sql.j2
        dest: /tmp/app_schema.sql
        owner: root
        group: root
        mode: '0644'

    - name: Importar esquema de la app en MySQL usando el usuario de la app
      community.mysql.mysql_db:
        state: import
        name: "{{ app_db.name }}"
        target: /tmp/app_schema.sql
        login_host: "{{ app_db.host }}"
        login_user: "{{ app_db.user }}"
        login_password: "{{ app_db.password }}"
