---
- name: Instalación base de Jenkins
  hosts: ci-cd
  become: true
  vars_files:
    - ../group_vars/jenkins.yml

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Java 17 y utilidades
      apt:
        name:
          - "{{ java_package }}"
          - wget
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Descargar clave GPG oficial Jenkins
      get_url:
        url: "{{ jenkins_gpg_key_url }}"
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Agregar repositorio de Jenkins
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: "{{ jenkins_repo_entry }}\n"
        mode: '0644'

    - name: Actualizar cache tras agregar Jenkins repo
      apt:
        update_cache: yes

    - name: Instalar Jenkins
      apt:
        name: "{{ jenkins_package }}"
        state: present
        update_cache: yes

    - name: Iniciar y habilitar Jenkins
      systemd:
        name: "{{ jenkins_service }}"
        state: started
        enabled: yes

    - name: Mostrar mensaje para completar el wizard manualmente
      debug:
        msg: |
          Jenkins ha sido instalado y arrancado en el puerto {{ jenkins_port }}.
          Por favor, abre tu navegador en http://<IP>:{{ jenkins_port }},
          introduce la Initial Admin Password y completa el wizard para crear 
          el usuario {{ jenkins_admin_user }} con contraseña 
          {{ jenkins_admin_password }}. Luego, ejecuta de nuevo este playbook 
          para instalar los plugins automáticamente.
      when: true