---
- name: Instalar y configurar OpenLDAP
  hosts: ldap
  become: true

  vars:
    ldap_domain:        cajacelia.es
    ldap_root_password: OtroPasswordSeguro
    ldap_organization:  CajaCelia

  tasks:
    - name: Instalar paquetes slapd y ldap-utils
      apt:
        name:
          - slapd
          - ldap-utils
        state: present
        update_cache: yes

    - name: Preseed slapd para configuración no interactiva
      debconf:
        name: slapd
        question: "{{ item.question }}"
        vtype:    "{{ item.vtype }}"
        value:    "{{ item.value }}"
      loop:
        - { question: "slapd/internal/adminpw",     vtype: "password", value: "{{ ldap_root_password }}" }
        - { question: "slapd/internal/generated_adminpw", vtype: "password", value: "{{ ldap_root_password }}" }
        - { question: "slapd/password1",            vtype: "password", value: "{{ ldap_root_password }}" }
        - { question: "slapd/password2",            vtype: "password", value: "{{ ldap_root_password }}" }
        - { question: "slapd/domain",               vtype: "string",   value: "{{ ldap_domain }}" }
        - { question: "slapd/organization",         vtype: "string",   value: "{{ ldap_organization }}" }

    - name: Reconfigurar slapd sin interacción
      command: dpkg-reconfigure -f noninteractive slapd
      args:
        creates: /etc/ldap/slapd.d/cn=config.ldif

    - name: Asegurar que slapd está iniciado y habilitado
      service:
        name: slapd
        state: started
        enabled: yes
